### ISSUE TITLE
How to use model with textures and colours?

### ISSUE THREAD

**Issue by rohang1411** [UCL/scikit-surgerytutorial01#27] opened 2022-01-17 14:36 UTC
Hey, I have a .obj model and I'm converting into .stl format to use it since .obj files are not supported. But in the process I'm loosing the colours and texture since .stl files don't have texture information. Can anyone please suggest how can I incorporate those as well in the overlay. Maybe by using any other format which supports colours and textures and is it supported by the code?

Also all the models I try come with red colour is there an option to change that?

**Comment by thompson318** [comment] 2022-01-20 09:49
Duplicate of https://github.com/UCL/scikit-surgerybard/issues/83

**Closed by thompson318** 2022-01-20 09:49 UTC
